### ISSUE TITLE
Fix LoadError on sqlite3_adapter in activerecord

### ISSUE THREAD

**Issue by mrkn** [red-data-tools/charty#103]
```
Error: test_index_name(TableActiveRecordTest::#index::.name): LoadError: Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.4), already activated sqlite3-2.0.1-x86_64-linux-gnu. Make sure all dependencies are added to Gemfile.
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/3.1.0/bundler/rubygems_integration.rb:280:in `block (2 levels) in replace_gem'
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.3/lib/active_record/connection_adapters/sqlite3_adapter.rb:14:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `require'
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:333:in `resolve_pool_config'
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.3/lib/active_record/connection_adapters/abstract/connection_handler.rb:134:in `establish_connection'
/opt/hostedtoolcache/Ruby/3.1.5/x64/lib/ruby/gems/3.1.0/gems/activerecord-7.1.3.3/lib/active_record/connection_handling.rb:53:in `establish_connection'
/home/runner/work/charty/charty/test/table/activerecord_test.rb:18:in `setup'
```

**Comment by mrkn** [comment]
@kou Do you have any knowledge about this?

**Comment by kou** [comment]
I've fixed it.

**Comment by mrkn** [comment]
Amazing! You’re incredible!!
