### ISSUE TITLE
examples/active_record.ipynb で LoadError: cannot load such file -- colors

### ISSUE THREAD

**Issue by hasimoto1009** [red-data-tools/charty#50]
https://github.com/red-data-tools/charty#development-with-docker の手順通り行い
# When using jupyter notebook
docker run -it -v ${PWD}:/charty -w /charty -p 8888:8888 charty-dev:0.1 を実行した

localhostにサーバーは立ち上がってアクセスできた
examples/active_record.ipynb にアクセスし
```
require 'charty'

charty = Charty::Plotter.new(:pyplot)
Charty::PyPlot.activate_iruby_integration
```
でrunボタンを押したときに以下のエラーが出力され実行できなかった

```
LoadError: cannot load such file -- colors
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/charty/lib/charty.rb:3:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
(pry):1:in `<main>'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:355:in `handle_line'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/backend.rb:66:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/backend.rb:12:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:87:in `execute_request'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:47:in `dispatch'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:37:in `run'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/home/jovyan/.gem/ruby/2.6.0/bin/iruby:23:in `load'
/home/jovyan/.gem/ruby/2.6.0/bin/iruby:23:in `<main>'
```

いったん日本語でサブミットします。

**Comment by kou** [comment]
`charty.gemspec`の`"red-colors"`の依存が`development_dependency`になっているのが問題な気がします。

常に必要なので`spec.add_dependency "red-colors"`じゃないとダメな気がします。

**Comment by 284km** [comment]
I Fixed by https://github.com/red-data-tools/charty/commit/8819014b8e01c48244fb6ed3f911cd494d454bcf and released v0.2.1.

@hasimoto1009 報告ありがとうございます！再び docker build して試していただくと、サンプルのコードが実行できます！

**Comment by hasimoto1009** [comment]
ありがとうございます！試してみます！

**Comment by mrkn** [comment]
@hasimoto1009 動作確認ができたらクローズしていただけると嬉しいです〜

**Comment by hasimoto1009** [comment]
```
git pull origin master
変更内容を確認

$ docker build -f ./Dockerfile.dev -t charty-dev:0.1 .
$ docker run --rm -v ${PWD}:/charty -w /charty charty-dev:0.1 bundle install --path vendor/bundle
$ docker run -it -v ${PWD}:/charty -w /charty -p 8888:8888 charty-dev:0.1
```
上記コマンドを実行しましたが結果は変わりませんでした

```
LoadError: cannot load such file -- colors
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/charty/lib/charty.rb:3:in `<top (required)>'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
(pry):1:in `<main>'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:355:in `handle_line'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'
/home/jovyan/.gem/ruby/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/backend.rb:66:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/backend.rb:12:in `eval'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:87:in `execute_request'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:47:in `dispatch'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/kernel.rb:37:in `run'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/command.rb:70:in `run_kernel'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/lib/iruby/command.rb:34:in `run'
/home/jovyan/.gem/ruby/2.6.0/gems/iruby-0.3/bin/iruby:5:in `<top (required)>'
/home/jovyan/.gem/ruby/2.6.0/bin/iruby:23:in `load'
/home/jovyan/.gem/ruby/2.6.0/bin/iruby:23:in `<main>'
```

自分の方でも触ってみます

**Comment by 284km** [comment]
@hasimoto1009 docker build に `--no-cache` オプションを付けて実行しても、変わりませんか？

**Comment by hasimoto1009** [comment]
`docker build -f ./Dockerfile.dev -t charty-dev:0.1 . --no-cache` で実行しましたが結果は変わりませんでした。

**Comment by mrkn** [comment]
私の手元の環境では再現できなかったです。

@hasimoto1009 Gemfile.lock を消すとどうなりますか？

**Comment by mrkn** [comment]
@hasimoto1009 ベースイメージや手順に少し手を入れたので、新しい master を使って試してみてください。

**Comment by hasimoto1009** [comment]
無事動作することを確認できました
ご対応ありがとうございました！
