### ISSUE TITLE
DataFrame plotting fails with categorical column and non-zero origin index

### ISSUE THREAD

**Issue by colspan** [red-data-tools/charty#93]
I found that Charty couldn't plot the DataFrame with categorical column and non-zero origin index.

```ruby
require 'charty'
require 'numo/narray'
require 'pandas'
data = Numo::DFloat.new(100, 3).seq
df = Pandas::DataFrame.new(data.to_a,
                           index: (300...400).to_a, # non-zero origin
                           columns: %w[a b c])
df[:categorical_column] = 'category_name'
# df[:categorical_column] = (200...300).to_a.map(&:to_s) # nothing changed

# works
Charty::Backends.use(:plotly)
plot = Charty.scatter_plot(
  data: df,
  x: :a,
  y: :b,
  color: :c, # numerical column
)
p plot

# not works
Charty::Backends.use(:plotly)
plot = Charty.scatter_plot(
  data: df,
  x: :a,
  y: :b,
  color: :categorical_column, # this is String based column
)
p plot
```

This example fails like this.

```
$ bundle exec ruby charty_test.rb 
#<Charty::Plotters::ScatterPlotter:0x00000000000006f4>
~/project/vendor/bundler/ruby/3.1.0/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `get_loc': <class 'KeyError'>: 0 (PyCall::PyError)
  File "~/project/venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
        from ~/project/vendor/bundler/ruby/3.1.0/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/index.rb:205:in `loc'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/vector_adapters.rb:160:in `key_to_loc'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/vector_adapters.rb:151:in `[]'
        from /home/kuni/.anyenv/envs/rbenv/versions/3.1.0/lib/ruby/3.1.0/forwardable.rb:238:in `[]'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/abstract_plotter.rb:188:in `variable_type'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/relational_plotter.rb:538:in `block in setup_variables'
        from /home/kuni/.anyenv/envs/rbenv/versions/3.1.0/lib/ruby/3.1.0/forwardable.rb:238:in `each'
        from /home/kuni/.anyenv/envs/rbenv/versions/3.1.0/lib/ruby/3.1.0/forwardable.rb:238:in `each'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/relational_plotter.rb:536:in `map'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/relational_plotter.rb:536:in `setup_variables'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/relational_plotter.rb:437:in `initialize'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plotters/scatter_plotter.rb:6:in `initialize'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plot_methods.rb:260:in `new'
        from ~/project/vendor/bundler/ruby/3.1.0/gems/charty-0.2.11/lib/charty/plot_methods.rb:260:in `scatter_plot'
        from charty_test.rb:23:in `<main>'
```

**Comment by kou** [comment]
@mrkn Could you take a look at this?

**Comment by mrkn** [comment]
@kou Yes, I've already began to work on this.
