### ISSUE TITLE
Charty::Backends::Pyplot.activate_iruby_integration gives AttributeError in JupyterLab

### ISSUE THREAD

**Issue by kozo2** [red-data-tools/charty#98]
```
require "charty"
Charty::Backends.use(:pyplot)
Charty::Backends::Pyplot.activate_iruby_integration
```

shows the following error message (for [this Dockerfile](https://github.com/kozo2/quarto4rubydata/blob/main/Dockerfile) Docker container.
This Dockerfile uses `rubydata/minimal-notebook:latest`).

```
PyCall::PyError: <class 'AttributeError'>: module 'matplotlib_rb.backend_inline' has no attribute 'FigureCanvas'
  File "/opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py", line 266, in switch_backend
    canvas_class = backend_mod.FigureCanvas

/home/jovyan/.local/share/gem/ruby/3.1.0/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `switch_backend'
/home/jovyan/.local/share/gem/ruby/3.1.0/gems/pycall-1.4.1/lib/pycall/pyobject_wrapper.rb:43:in `method_missing'
/home/jovyan/.local/share/gem/ruby/3.1.0/gems/matplotlib-1.2.0/lib/matplotlib/iruby.rb:201:in `activate_matplotlib'
/home/jovyan/.local/share/gem/ruby/3.1.0/gems/matplotlib-1.2.0/lib/matplotlib/iruby.rb:152:in `enable_matplotlib'
/home/jovyan/.local/share/gem/ruby/3.1.0/gems/matplotlib-1.2.0/lib/matplotlib/iruby.rb:111:in `activate'
/home/jovyan/.local/share/gem/ruby/3.1.0/gems/charty-0.2.12/lib/charty/backends/pyplot.rb:24:in `activate_iruby_integration'
(irb):in `<top (required)>'
​
```

Tell me if you have any ideas about resolving this error.

**Comment by mrkn** [comment]
@kozo2 Thank you for your feedback.  It must be an issue of matplotlib.rb.

**Comment by mrkn** [comment]
I filed the issue https://github.com/mrkn/matplotlib.rb/issues/18.
